# 指定 docker-compose 文件格式的版本
version: '3.8'

# 定义组成应用的所有服务（容器）
services:
  # MySQL 服务
  mysql-db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123
      MYSQL_DATABASE: web_project_db
      MYSQL_USER: user_123
      MYSQL_PASSWORD: password_123
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Redis 服务
  redis:
    image: redis:latest
    restart: unless-stopped
    # 端口映射，对应命令中的 -p 6379:6379
    ports:
      - "6379:6379"
    # Redis 启动参数，对应命令中的 --requirepass "123456"
    command: redis-server --requirepass "123456"

# 数据卷定义
volumes:
  mysql-data: